Add peglib grammar
emerald-lang/emerald pull request #63
Opened 2017-07-08 22:35 UTC by davepagurek

This converts our old Treetop grammar to a Peglib grammar. Since Peglib expects a string as input, the peg files need to get concatenated into a single string. Each `.peg` file is a C++ string literal (hence the `R"( ... )"` surrounding the contents of each.)

This also adds more tests to the preprocessor to ensure bracketing happens correctly.

2017-07-10 07:13 UTC, AndrewMcBurney commented on cpp/src/preprocessor.cpp
> +  for (int i = 2; i <= (current_indent - new_indent) / 2; i++) {
Good catch 👍

2017-07-10 07:15 UTC, AndrewMcBurney commented
LGTM, but let's try to figure out why the tests are failing - I checked CircleCI, and I'm kinda stumped. My guess is it has something to do with our CircleCI `circle.yml` setup. Crazy how nature do dat 🤔

2017-07-12 02:23 UTC, armcburney requested changes
😳

2017-07-12 02:23 UTC, AndrewMcBurney commented on cpp/src/grammar.hpp
> +public:
Yo, could you please put this public stuff up with the other public code at the top of the class 💯🙏

2017-07-12 02:23 UTC, AndrewMcBurney commented on cpp/src/preprocessor.cpp
> +  for (unsigned int line_number = 0; line_number < lines.size(); line_number++) {
Why did you make this `unsigned` - just curious?

2017-07-12 03:21 UTC, davepagurek commented on cpp/src/preprocessor.cpp
> +  for (unsigned int line_number = 0; line_number < lines.size(); line_number++) {
lol no idea, must have been debugging something. no warnings or anything without it. gone now

2017-07-12 03:21 UTC, davepagurek commented on cpp/src/grammar.hpp
> +public:
I think this is another leftover debugging thing, it can be private actually. Removed this

2017-07-12 04:11 UTC, armcburney approved these changes
🍻

2017-07-13 00:23 UTC, merged