Add the rest of the nodes
emerald-lang/emerald pull request #81
Opened 2017-07-28 04:13 UTC by davepagurek

This makes two new base classes:
- `Boolean`, for things in the condition of a `ScopeFn`
- `ScopeFn`, which takes a `NodePtr` in addition to a `Json` in its `to_html` method. It transforms the context and passes it to the `NodePtr`.

Some refactors done in the process:
- Refactored `TagStatement` and `Nested` into one class
- Took the `const` out of the `Json` typedef so that we can use it mutably to build up a new context in a `ScopeFn`. After we're good with all the nodes, we should change the `to_html` signature to take in a `const Json` (we were going to refactor it anyway to add `const` to the method.) Added this to https://github.com/emerald-lang/emerald/issues/78

Things left to do after this:
- I can't `make` the whole thing because there are some other build errors right now, so probably when we fix the existing ones, we'll discover new build errors in this code.
- Our current code for repeated rules will need to be changed, unfortunately. https://github.com/emerald-lang/emerald/issues/80

2017-07-28 04:18 UTC, AndrewMcBurney commented on cpp/src/grammar.cpp
> +        new TagStatement(tag_name, id_name, class_names, body, attributes, nested));
Just curious - why did you put this on a new line?

2017-07-28 04:28 UTC, davepagurek commented on cpp/src/grammar.cpp
> +        new TagStatement(tag_name, id_name, class_names, body, attributes, nested));
It was getting a little long

2017-07-28 04:36 UTC, davepagurek commented on cpp/src/grammar.cpp
> +        new TagStatement(tag_name, id_name, class_names, body, attributes, nested));
I also added another parameter to the list, btw, which is what made me think to bump it down a line

2017-07-28 04:37 UTC, AndrewMcBurney commented on cpp/src/grammar.peg
> +tag_statement          <- tag id_name? class_name* ~space* text_content? attr_list? (~nl ~lbrace ~nl ROOT ~rbrace ~nl)?
👍 💯

2017-07-28 04:38 UTC, AndrewMcBurney commented on cpp/src/nodes/binary_expr.hpp
> +
can you remove this blank newline please?

2017-07-28 04:38 UTC, AndrewMcBurney commented on cpp/src/nodes/binary_expr.hpp
> +  Operator op;
And add a blank newline after line 23?

2017-07-28 04:40 UTC, AndrewMcBurney commented on cpp/src/nodes/each.cpp
> +std::string Each::to_html(NodePtr body, Json &context) const {
This method is kinda big, and hard to read - do you think we could break this up into a few smaller private methods belonging to the `Each` class?

2017-07-28 04:41 UTC, AndrewMcBurney commented on cpp/src/nodes/scope.cpp
> +  return scope_fn->to_html(body, context);
Good catch 👍

2017-07-28 04:41 UTC, AndrewMcBurney commented on cpp/src/nodes/each.hpp
> +  std::string key_name;
Could we add a blank newline after this statement?

2017-07-28 04:45 UTC, AndrewMcBurney commented on cpp/src/nodes/tag_statement.cpp
> +  NodePtr attributes,
So we renamed the `attributes` rule to the `attr_list` rule [here](https://github.com/emerald-lang/emerald/pull/81/files#diff-c33c4b016c1880061bfb23d9f65a525fR130). Should we call this `attr_list` in this class as well as [here](https://github.com/emerald-lang/emerald/pull/81/files#diff-c33c4b016c1880061bfb23d9f65a525fR127) to be consistent?

2017-07-28 04:46 UTC, AndrewMcBurney commented on cpp/src/nodes/unary_expr.hpp
> +  BooleanPtr expr;
Could we add a newline after here?

2017-07-28 04:47 UTC, AndrewMcBurney commented on cpp/src/scopes.peg
> +unary_expr   <- ('not' space+)? (variable_name / ~'(' ~space* boolean_expr ~space* ~')')
👍

2017-07-28 04:47 UTC, AndrewMcBurney commented on cpp/src/scopes.peg
> +binary_expr  <- unary_expr ~space+ ('and' / 'or') ~space+ boolean_expr
👍

2017-07-28 04:47 UTC, AndrewMcBurney commented on cpp/src/scopes.peg
> +each         <- ~'each' ~space* variable_name ~space* ~'as' ~space* ~variable_name (~',' ~space* ~variable_name)? >
👍

2017-07-28 04:48 UTC, armcburney requested changes
Fantastic work 🙌 - just a few minor things, which I commented above.

2017-07-28 05:36 UTC, armcburney approved these changes
We'll start using an autoformatter for C++ once we get the grammar working.

2017-07-29 21:37 UTC, armcburney approved these changes
:100: :shipit:

2017-07-29 21:48 UTC, merged